= Auth & Profile

Dikerjakan oleh Backend Engineer & Frontend Engineer.

== Main

Pada bagian main ini, pertama tama yang saya lakukan adalah mengaktifkan Firebase agar aplikasi bisa terhubung dengan layanan login dan database. Setelah itu saya menjalankannya dengan memanggil myapp.

Di dalam MyApp, saya pakai MaterialApp untuk mengatur tema aplikasi, seperti warna biru sebagai warna utama, font Poppins, dan menghilangkan tulisan debug di pojok. Halaman awalnya saya arahkan ke initialScreen.

Nah, di initialScreen saya membuat logika untuk menentukan halaman pertama yang muncul. Disini saya menggunakan sharedpreferences yang menyimpan user id. Kalau masih loading, tampil indikator bulat. Kalau pengguna ada di sharedpreferences, maka langsung diarahkan ke HomePage. Sedangkan kalau user id di sharedpreferences tidak ada, otomatis diarahkan ke LoginPage.

== Auth Register

Pada bagian ini saya membuat sebuah halaman yang memungkinkan pengguna bisa mendaftarkan diri di aplikasi CinemaPro. Yang mana nanti yang akan diinputkan adalah email, username, password, dan confirm password untuk konfirmasi apakah password yang diinputkan sama. Disini saya juga menambahkan sistem validasi, seperti pada email, saya menambahkan aturan bahwa alamat harus menggunakan domain kampus student.univ.ac.id, sehingga hanya mahasiswa yang bisa mendaftar dan masuk.

#image("../images/register-normal.png", width: 50%)

#image("../images/register-ditolak.png", width: 50%)

=== Validasi Email Mahasiswa
Bagian validasi email dikerjakan oleh Rusydi Jabir Al Awfa (Frontend Engineer - Seat Matrix Module). Sistem validasi email menggunakan Regular Expression untuk memastikan bahwa hanya alamat email dengan domain @student.univ.ac.id yang dapat digunakan untuk registrasi. Berikut adalah implementasi dari EmailValidator:

```dart
/// Utility class for email validation
class EmailValidator {
  /// Validates if an email is in the format required: @student.univ.ac.id
  static bool isValidStudentEmail(String email) {
    // Regex pattern to match emails ending with @student.univ.ac.id
    RegExp emailRegex = RegExp(r'^[a-zA-Z0-9._%+-]+@student\.univ\.ac\.id$');
    return emailRegex.hasMatch(email);
  }
}
```

=== Hashing Password
Untuk keamanan data pengguna, password di-hash sebelum disimpan ke database. Implementasi hashing password juga dikerjakan oleh Rusydi Jabir Al Awfa menggunakan algoritma SHA256 dengan salt dari hash key di file .env:

```dart
import 'dart:typed_data';
import 'dart:convert';
import 'package:crypto/crypto.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

class PasswordHashUtil {
  /// Hash a password using SHA256 algorithm with the project's secret key as salt
  static Future<String> hashPassword(String password) async {
    // Load the hash key from .env file
    await dotenv.load(fileName: ".env");
    String hashKey = dotenv.env['HASH_KEY'];

    // Create salted password
    String saltedPassword = password + hashKey;

    // Hash using SHA256
    var bytes = utf8.encode(saltedPassword);
    var digest = sha256.convert(bytes);

    return digest.toString(); // Returns hex representation of the hash
  }
}
```

=== User Service
Bagian UserService yang bertugas untuk menyimpan data pengguna ke Firestore juga dikerjakan oleh Rusydi Jabir Al Awfa:

```dart
class UserService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Create a new user with hashed password
  Future<bool> createUserWithPassword({
    required String email,
    required String username,
    required String password,
  }) async {
    try {
      // Hash the password
      String hashedPassword = await PasswordHashUtil.hashPassword(password);

      // Generate a new document ID for the user
      String newUid = _firestore.collection('users').doc().id;

      // Create user profile in Firestore using the existing user model
      UserModelCheryl newUser = UserModelCheryl(
        uid: newUid, // Primary Key (auto-generated by Firestore)
        email: email.trim(), // Validated with @student.univ.ac.id regex
        username: username.trim(), // Display name
        balance: 200000, // Default balance (200000), as specified
        password: hashedPassword, // Store hashed password
      );

      // Create user profile in Firestore with all required fields
      await _firestore.collection('users').doc(newUid).set({
        ...newUser.toMapCheryl(), // Use the model's toMap method
        'createdAt': FieldValue.serverTimestamp(), // Server timestamp for accuracy
      });

      return true;
    } catch (e) {
      print('Error creating user: $e');
      return false;
    }
  }
}
```

== Auth Login

Pada bagian login ini saya membuat sebuah halaman yang memungkinkan pengguna masuk ke aplikasi menggunakan akun yang sudah terdaftar di Firebase. Tampilan login ini terdiri dari dua input utama, yaitu email dan password, yang masing-masing dilengkapi dengan validasi. Untuk email, saya menambahkan aturan bahwa alamat harus menggunakan domain kampus student.univ.ac.id, sehingga hanya mahasiswa yang bisa mendaftar dan masuk.

#image("../images/login.png", width: 50%)

Berikut kode untuk form login dengan validasi. Form ini menggunakan FormKey untuk validasi dan TextEditingController untuk mengambil input dari pengguna.

Selain itu, saya menambahkan logika agar ketika tombol Login ditekan, aplikasi terlebih dahulu memvalidasi form. Jika valid, maka saya akan memanggil fungsi finduser yang sebelumnya sudah dibuat oleh jabir. Selama proses ini berlangsung, tombol login diganti dengan indikator loading agar pengguna tahu bahwa proses sedang berjalan. Jika login berhasil, muncul pesan Login berhasil dengan warna hijau, lalu pengguna diarahkan ke halaman utama HomePage dan data login pengguna tersebut juga saya simpan di sharedpreferences yaitu uid nya. Sebaliknya, jika login gagal, sistem menampilkan pesan error berwarna merah.

Di bagian bawah halaman, saya juga menyediakan opsi bagi pengguna yang belum memiliki akun. Terdapat teks Tidak memiliki akun dengan tombol Register yang akan mengarahkan pengguna ke halaman pendaftaran. Dengan cara ini, halaman login tidak hanya berfungsi untuk login saja, tetapi juga menjadi navigator bagi pengguna baru untuk membuat akun.

#image("../images/loginNavigatorRegister.png", width: 50%)

== Profile

Halaman profile untuk menampilkan identitas pengguna dan menampilkan riwayat transaksi. Pertama, untuk bagian header profil, saya menggunakan FutureBuilder untuk mengambil data detail pengguna (Username, Email dan saldo) dari collection users berdasarkan UID pengguna yang sedang login, kemudian data diambil dan di konversi menggunakan UserModelCheryl.

Kedua, untuk bagian Riwayat Tiket, saya menggunakan StreamBuilder. Penggunaan Stream dipilih agar daftar tiket dapat diperbarui secara real-time tanpa perlu me-refresh halaman jika ada transaksi baru. Saya menerapkan query filtering menggunakan where untuk memastikan pengguna hanya melihat tiket miliknya sendiri.

Selain itu, sesuai spesifikasi teknis, saya mengimplementasikan library qr_flutter untuk generate QR CODE secara otomatis berdasarkan booking_id dari setiap transaksi.

#image("../images/HistoryPage.jpeg", width: 50%)